### ISSUE TITLE
Width and height of custom entities

### ISSUE THREAD

**Issue by mattias-p** [christopho/solarus-quest-editor#169]
It seems solarus and solarus-quest-editor v1.4 agree that the width and height fields of custom entities in map data files are optional (with a default value of 16). However, the map data file reference indicates that these fields are required. Either the documentation or the code should be updated.

**Comment by christopho** [comment]
Users who use the development version of 1.5 should re-convert all their maps from 1.4 to 1.5. Otherwise, maps that have custom entities may fail to open.

To do so:
- Make a backup of your quest.
- Manually set solarus_version to "1.4" in quest.dat with a text editor.
- Open your quest in the editor: the editor will convert to 1.5 again
  to the correct format.

(Don't worry, whatever was already converted before will be preserved).
