### ISSUE TITLE
Let the user choose what type of tile an absence of tiles is interpreted to be

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus-quest-editor#174]
It would be useful if you could set that "no tile" is treated as walls instead of traversable, e.g. for demo purposes.

**Comment by christopho** [comment]
No entity is treated as empty because there is nothing. I understand the problem, but this is not a good solution. Also, maps can have several layers, they are all empty initially and we don't want to change that.

If you need a background wall, use a big wall tile. I know it is annoying sometimes to have a big background tile but
- you can ignore it when selecting entities, if you press Ctrl or Shift before selecting,
- there is a feature request to "lock" tiles, the exact definition remains to be decided but I hope it can help with this use case,
- there is a feature request to change the Z order of entities more accurately than just "bring to back" / "bring to front".
