### ISSUE TITLE
Feature Request: Tileset editor border to 1x1 would make it a pixel art creator

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#185]
If the tileset editor was not limited to 8x8, then it could be used to make pixel art with a color palette image. Number #180 could make this happen.

**Comment by christopho** [comment]
I don't understand :)

**Comment by Zefk** [comment]
It could be made to create sprites. Especially if a  merge feature is added. 1x1 pixel areas of a color palette could be selected.
![sprite made with tileset editor](https://cloud.githubusercontent.com/assets/19560764/15792699/beec564a-2993-11e6-8427-d14cf1432112.png)

![dawnbringer 16 color palette - db16_v1_analyze](https://cloud.githubusercontent.com/assets/19560764/15792480/5d58a9ca-2992-11e6-8639-29914976e79e.png)

**Comment by alexander-b** [comment]
I think this is largely out of scope for the quest editor. It should certainly not be a high priority for now. It would never be as good as using a dedicated pixelart editor anyway. Although I can agree that it would be good to have some rudimentary support for it, so that complete newbies to pixelart can make *something* without having to learn a proper pixelart tool.

**Comment by christopho** [comment]
I agree with @alexander-b. A pixel art editor might be nice one day, but not prioritary.
And definitely separated from the map editor.
