### ISSUE TITLE
The console cannot be resized when a sprite editor is open

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#215]
In the version for Windows, if there are open tabs you cannot resize the console (unless you close all the tabs), which is too bad. I guess this is a bug.

**Comment by christopho** [comment]
The problem seems to be windows specific. Only affects the console of the quest editor, not the one of the launcher.

**Comment by christopho** [comment]
I just made some tests. The bug is not Windows-specific, but only happens when one of the open tabs is a sprite editor. The sprite editor has a quite big minimum height, causing the problem. This is annoying because even if the active tab is not a sprite editor, the console cannot be resized if there is a sprite editor tab elsewhere.

@Diarandor can you confirm that you don't have the bug when no tab is a sprite editor?

**Comment by Diarandor** [comment]
I confirnm that. It only happens if some tab is using the sprite editor, and otherwise there is no problem.
